wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/exps/NAS-Bench-201-algos/TNAS.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    start_time: 1653636522
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 3
      - 13
      - 15
      - 16
      4: 3.6.8
      5: 0.12.9
      8:
      - 5
commit:
  desc: null
  value: 33ff2eac711a150d499a4333d7bbbec6a5914cac
run_path:
  desc: null
  value: /home/qiang/codefiles/doing/nas/TNAS
